"""Second migration

Revision ID: bf289e0c8174
Revises: 6d7098ef0cdf
Create Date: 2024-02-26 18:07:38.110771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf289e0c8174'
down_revision = '6d7098ef0cdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
